# Generated by Django 3.2.12 on 2022-08-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='ch1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ques',
            name='ch2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ques',
            name='ch3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ques',
            name='ch4',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
