# Generated by Django 3.2.12 on 2022-08-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll1', '0003_auto_20220826_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='re',
            name='vote1',
        ),
        migrations.RemoveField(
            model_name='re',
            name='vote2',
        ),
        migrations.RemoveField(
            model_name='re',
            name='vote3',
        ),
        migrations.RemoveField(
            model_name='re',
            name='vote4',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote4',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
