# Generated by Django 3.2.12 on 2022-08-27 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll1', '0004_auto_20220827_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='vote1',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote2',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote3',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote4',
        ),
    ]
