# Generated by Django 3.2.12 on 2022-08-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll1', '0007_auto_20220827_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='re',
            name='vote1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='re',
            name='vote2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='re',
            name='vote3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='re',
            name='vote4',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
