# Generated by Django 3.2.12 on 2022-08-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll1', '0008_auto_20220827_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ques',
            name='vote1',
        ),
        migrations.RemoveField(
            model_name='ques',
            name='vote2',
        ),
        migrations.RemoveField(
            model_name='ques',
            name='vote3',
        ),
        migrations.RemoveField(
            model_name='ques',
            name='vote4',
        ),
    ]
