# Generated by Django 3.2.12 on 2022-08-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll1', '0009_auto_20220827_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='re',
            name='vote2',
        ),
        migrations.RemoveField(
            model_name='re',
            name='vote3',
        ),
        migrations.RemoveField(
            model_name='re',
            name='vote4',
        ),
    ]
