# Generated by Django 3.2.12 on 2022-08-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll1', '0011_auto_20220828_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='vote1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ques',
            name='vote2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ques',
            name='vote3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ques',
            name='vote4',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
